# Generated by Django 3.1.7 on 2021-03-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000000)),
                ("publishedAt", models.DateTimeField()),
                ("videoId", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name="videodetails",
            index=models.Index(fields=["title"], name="sample_app__title_89d093_idx"),
        ),
        migrations.AddIndex(
            model_name="videodetails",
            index=models.Index(
                fields=["description"], name="sample_app__descrip_468acb_idx"
            ),
        ),
    ]
